[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_options = "3JZ99S1BGfcdExZ4immxWKSGAFkbe3hxZo9NRxvrair4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.secrets/payer.json"

[scripts]
test = "npm run test"
