[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_options = "So1ar1uyyJ2bhm4DTN3M2wWkug4trVknn2kdZ2vD2Vh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.secrets/seller.json"

[scripts]
test = "npm run test"
